### ISSUE TITLE
Pick Up商品

### ISSUE THREAD

**Issue by shmn7iii** [shmn7iii/monoiroha#12]
## 概要
- 得票数の多いユーザーの商品を「Pick Up商品」に出す
  - 「Pick Up商品」はトップページ上部
- 上位4人の商品1つずつ、計4商品
  - スペースに余裕がありそうなら2つずつ、計8商品

## 参考
`user.number_of_votes` で得票数が取得できるはず

**Comment by kimjunhyeok18** [comment]
close
