### ISSUE TITLE
「所持トークン総数」の表示場所、邪魔では？

### ISSUE THREAD

**Issue by shmn7iii** [shmn7iii/monoiroha#21]
## 概要
- Ref. #20 
<img width="1347" alt="スクリーンショット 2022-11-02 午前8 25 51" src="https://user-images.githubusercontent.com/46078198/199360768-ff73234b-d02f-499a-92d7-ae9a05a6d761.png">

邪魔では？

**Comment by motoha0827** [comment]
tokens_controller を作成
indexアクション作ってsharedの_tokens.html.slimを流用。
